export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as PropertyDetails } from "./PropertyDetails";
export { default as Properties } from "./Properties";
export { default as Blogs } from "./Agencies";
export { default as Contact } from "./Contact";
export { default as Team } from "./Team";
export { default as Faqs } from "./Faqs";
export { default as PageNotFound } from "./PageNotFound";
